system:
  verbose: false
  tuning: false
  videoPort: 1181
  robotPort: 1183
  receivePort: 1184
vision:
  lowHue: 0
  lowSaturation: 0
  lowValue: 214
  highHue: 255
  highSaturation: 99
  highValue: 255
  dilationPasses: 0
  minArea: 20
  maxArea: 7500
  minContourToBoundingBoxRatio: 0
  maxContourToBoundingBoxRatio: 0.5
  allowableError: 3
uvccam:
  width: 320
  height: 240
  everyNthFrame: 2
  exposure: 0
  exposureAuto: 3
raspicam:
  width: 640
  height: 480
  sensorMode: 7
  fps: 15
  sharpness: 0
  contrast: 0
  brightness: 50
  saturation: 0
  shutterSpeed: 50000
  whiteBalanceMode: 3
  exposureMode: 0
  exposureCompensation: 0
  horizontalFov: 75
