system:
  verbose: false
  tuning: true
  videoPort: 1181
  robotPort: 1183
  receivePort: 1184
vision:
  lowHue: 0
  lowSaturation: 0
  lowValue: 99
  highHue: 255
  highSaturation: 73
  highValue: 255
  dilationPasses: 1
  minArea: 20
  maxArea: 30000
  minContourToBoundingBoxRatio: 0.17000000000000001
  maxContourToBoundingBoxRatio: 0.45000000000000001
  allowableError: 3
uvccam:
  width: 320
  height: 240
  dropEveryNthFrame: 0
  exposure: 0
  exposureAuto: 3
raspicam:
  width: 320
  height: 240
  sensorMode: 7
  maxFps: 0
  sharpness: 0
  contrast: 0
  brightness: 50
  saturation: 0
  shutterSpeed: 50000
  whiteBalanceMode: 8
  exposureMode: 0
  exposureCompensation: 0
